[package]
name = "icomoon_font_icons"
version = "1.0.0"
edition = "2021"
crate_type = ["lib"]
rustdocflags = ["--html-after-content", "src/rustdoc.html"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
